### ISSUE TITLE
http://www.backup-manager.org/ taken over?

### ISSUE THREAD

**Issue by hartwork** [sukria/Backup-Manager#55] opened 2015-08-20 21:14 UTC
It looks like http://www.backup-manager.org/ has been taken over.
Please consider fixing links to it, e.g. the on in the GitHub header.
Thanks and best, Sebastian

**Comment by llaumgui** [comment] 2015-10-16 11:12
Duplicate of #24

**Closed** 2016-01-23 20:22 UTC
